language: go
go:
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master
    - fast_finish: true

before_script :
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 .
  - golint -set_exit_status $(go list ./...)
